name: Upload

on:
  push :
    tags :
      - v1.*

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo ${{github.sha}} > artifact/sha
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: artifact
